### ISSUE TITLE
Package.loadSettings is deprecated.

### ISSUE THREAD

**Issue by appkery** [m1ga/language-tss#1]
While it still works, I got 2 deprecated calls.

`atom core (1 deprecation)`
Use `activationCommands` instead of `activationEvents` in your package.json Commands should be grouped by selector as follows:
```
  "activationCommands": {
    "atom-workspace": ["foo:bar", "foo:baz"],
    "atom-text-editor": ["foo:quux"]
  }
```
Called 1 time
```
Package.getActivationCommands - /Applications/Atom.app/Contents/Resources/app/src/package.js:777:9
Package.hasActivationCommands - /Applications/Atom.app/Contents/Resources/app/src/package.js:702:20
```

`language-tss (1 deprecation)`
Store package settings files in the `settings/` directory instead of `scoped-properties/`
Called 1 timeCreate Issue on language-tss repo
```
Package.loadSettings - /Applications/Atom.app/Contents/Resources/app/src/package.js:565:9
<unknown> - /Applications/Atom.app/Contents/Resources/app/src/package.js:187:43
```

**Comment by m1ga** [comment]
thanks! I'll have a look soon and fix it

**Comment by m1ga** [comment]
the first one is "atom core (1 deprecation)" but I've fixed the second one.
